### ISSUE TITLE
Further Plans

### ISSUE THREAD

**Issue by JasonGrace2282** [JasonGrace2282/xpire-tray#3]
This issue serves as a tracker issue for the future plans of this repository.

## Urgent
- [ ] Improve Infrastructure
- [ ] Add tests for behavior (CI tests as well)
- [ ] Replace LogMean API for custom implementation
- [ ] Implement Custom Database of expiry foods (webscraping?)
- [ ] Figure out how to package

## Future Ideas
- [ ] Move to organization
- [ ] Rewrite in Dart to turn into a mobile app
- [ ] Integrate with storage containers such as fridges/pantries
- [ ] Optimize/Reduce Dependencies
